<div class="col-md-12">
    <div class="jumbotron">
        <h3 class="text-center">
            Método de Transporte
        </h3>
    </div>
    <div class="row">
        <div class="col-md-4">
            <ul class="list-group">
                <li><a href="<?php echo Link::ruta(); ?>transporte/concepto" >Concepto</a></li>
                <li><a href="<?php echo Link::ruta(); ?>transporte/esquinanoroeste" >Método de la Esquina Noroeste</a></li>
                <li><a href="<?php echo Link::ruta(); ?>transporte/vogel" >Método de Vogel</a></li>
            </ul>
        </div>
        <div class="col-md-8">
            
        <?php view(Request::get_method(), $transporte); ?>


        </div>
    </div>
</div>