<div class="col-md-12">
    <div class="jumbotron">
        <h3 class="text-center">
            Método de Transporte
        </h3>
    </div>
    <div class="row">
        <div class="col-md-4">
            <ul class="list-group">
                <li><a href="<?php echo Link::ruta(); ?>transporte/concepto" >Concepto</a></li>
                <li><a href="<?php echo Link::ruta(); ?>transporte/esquinanoroeste" >Método de la Esquina Noroeste</a></li>
                <li><a href="<?php echo Link::ruta(); ?>transporte/vogel" >Método de Vogel</a></li>
            </ul>
        </div>
        <div class="col-md-8">
            
        <?php
        if(empty(Request::get_args())){
            view(Request::get_method(), $transporte); 
        }else{
            img(Request::get_args());
            ?>
            <br><br>
            <ol>
            <?php
            for($i=0;$i<6;$i++){
                ?>
                    <li><a href="<?php echo Link::ruta(); ?>transporte/ejemplo/<?php echo $i + 1; ?>">Imagen <?php echo $i + 1; ?></a></li>
                <?php
        
            }
            ?>
            </ol>
            
            <?php
        }
                ?>

        </div>
    </div>
</div>