<div class="col-md-12">
    <div class="jumbotron">
        <br>
        <br>
        <h1 class="text-center text-success">
            ..:: Programación Lineal  ::..
        </h1>
        <br>
        <br>
        <br>
        
        
        <p class="text-right">Integrantes:
        <ul class="list-group text-right">
            <li class="list-group-item">Yeimi Ortiz, C.I.V-</li>
            <li class="list-group-item">Argenis Vargas, C.I.V-18.188.043</li>
            <li class="list-group-item">Alejandro Betanco, C.I.V-26.000.000</li>
        </ul>    
        </p>

        <h3 class="text-center">
            <a class="btn btn-default" href="<?php echo Link::ruta(); ?>inicio">Siguiente</a>
        </h3>
        
    </div>
    
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<script>
$(document).ready(function(){
    $("body").hide().fadeIn(5000);
});
</script>
