<div class="col-md-12">
    <div class="jumbotron">
        <h3 class="text-center">
                Programación Lineal 
        </h3>
    </div>
    <div class="row">
        <div class="col-md-6">
        
        <p class="text-justify">
        <?php echo $pl['concepto']; ?>
        </p>
        </div>
        <div class="col-md-6"><br>
            <center>
                <img class="img-thumbnail" src="<?php echo Link::ruta(); ?>assets/imgs/p_lineal.jpg" alt="Programación Lineal">
            </center>
        </div>
    </div>
</div>

